matrix_tests : 
	g++ -std=c++17 -o matrix Matrix_tests.cpp Matrix.cpp Matrix.hpp
regression_tests : 
	g++ -std=c++17 -o regression RegressionModels_tests.cpp RegressionModels.cpp RegressionModels.hpp Matrix.cpp Matrix.hpp
